// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ftgxvpzvbhwamwomhjlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0Z3h2cHp2Ymh3YW13b21oamxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzYyNjIsImV4cCI6MjA2NjUxMjI2Mn0.f55WJYcITpnaxdtCxn9yG6s5tsUcusMY0xRU_2nZsD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);