// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgjepvtycvprgftspgfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxnamVwdnR5Y3ZwcmdmdHNwZ2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzQ3NTUsImV4cCI6MjA2NjUxMDc1NX0.EiS01dkCihhdHQDLugPo4z4q8WKdxjbP-8ub4yLTuN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);